### ISSUE TITLE
开启SetBlockRef(true)后MarkdownStr 报错

### ISSUE THREAD

**Issue by 2234839** [88250/lute#114]
### 描述问题 Describe the problem
在 go 中使用 `luteEngine.SetBlockRef(true)` 然后调用 `luteEngine.MarkdownStr` 会报错

### 其他信息 Other information

![图片](https://user-images.githubusercontent.com/28727933/99951181-a0cdb400-2db8-11eb-9c8e-7da224ab099c.png)

错误栈
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1108d76]

goroutine 1 [running]:
github.com/88250/lute/parse.(*Context).closeUnmatchedBlocks(0xc000311290)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/parse/parse.go:142 +0x76
github.com/88250/lute/parse.(*Tree).incorporateLine(0xc000b9eb40, 0xc00033f61d, 0x1, 0x1e3)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/parse/blocks.go:147 +0x6f6
github.com/88250/lute/parse.(*Tree).parseBlocks(0xc000b9eb40)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/parse/blocks.go:45 +0xa1a
github.com/88250/lute/parse.Parse(0x0, 0x0, 0xc00033f100, 0x60f, 0x700, 0xc0000a41a0, 0xc000b9eb40)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/parse/parse.go:27 +0x265
github.com/88250/lute.(*Lute).Markdown(0xc00017e0c0, 0x0, 0x0, 0xc00033f100, 0x60f, 0x700, 0x0, 0x0, 0x0)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/lute.go:112 +0xae
github.com/88250/lute.(*Lute).MarkdownStr(0xc00017e0c0, 0x0, 0x0, 0xc00033ea00, 0x60f, 0x0, 0x0)
	C:/Users/llej/go/pkg/mod/github.com/88250/lute@v1.6.6/lute.go:123 +0xbc
main.main()
	d:/code/md2website/src/main.go:116 +0x13a5
Process exiting with code: 0
```

**Comment by 88250** [comment]
麻烦贴一下 Markdown 文本。

**Comment by 2234839** [comment]
> 
> 
> 麻烦贴一下 Markdown 文本。

这一篇

思源笔记用户指南\使用内容块\🌈 内容块动态查询_20201117101902-2ewjjum.sy.md

是嵌入块查询的问题？

**Comment by 88250** [comment]
有可能，标准 HTML 渲染器没怎么做，等会看。

**Comment by 88250** [comment]
加了个测试用例 https://github.com/88250/lute/blob/master/test/block_query_embed_test.go

思源用户指南那篇全文也测过，似乎没有报错。

**Comment by 2234839** [comment]
> 
> 
> 加了个测试用例 https://github.com/88250/lute/blob/master/test/block_query_embed_test.go
> 
> 思源用户指南那篇全文也测过，似乎没有报错。

但我这里也确实报错了，你要不看下我的代码？ https://github.com/2234839/md2website/blob/main/src/main.go

**Comment by 88250** [comment]
麻烦用刚刚那个测试用例跑了看……

**Comment by 2234839** [comment]
> 
> 
> 麻烦用刚刚那个测试用例跑了看……

这个测试用例在我这也是报错的，是不是 lute 版本问题，我这是用的是 1.6.6 的

**Comment by 88250** [comment]
哦，那应该是，更新到最新 master 代码看。

**Comment by 2234839** [comment]
> 
> 
> 哦，那应该是，更新到最新 master 代码看。

go 可以指定引入的依赖实际所在的位置吗？

**Comment by 88250** [comment]
go.mod 里最后加类似这样的本地路径：

```
replace github.com/88250/lute => D:\gogogo\src\github.com\88250\lute
```

![image](https://user-images.githubusercontent.com/873584/99960062-1b053500-2dc7-11eb-8b9b-ca94ff8d1830.png)

**Comment by 2234839** [comment]
可以了
