### ISSUE TITLE
ToC 生成的 HTML 结构使用 ul li

### ISSUE THREAD

**Issue by sunlightcs** [88250/lute#115]
现在是这样的：
![image](https://user-images.githubusercontent.com/354173/100033431-2bec8f80-2e35-11eb-9441-6f7f6df0b37c.png)

建议改成这样：
![image](https://user-images.githubusercontent.com/354173/100033538-5a6a6a80-2e35-11eb-9e78-c793e2fb18fb.png)

**Comment by 88250** [comment]
麻烦说下原因，谢谢。

**Comment by sunlightcs** [comment]
这样可以通过样式控制，层级也更清晰，而不是通过占位符，像marked也是这样处理的

**Comment by 88250** [comment]
好的，明白了，这个估计要稍微等一阵子，谢谢。

**Comment by 88250** [comment]
基本已经修改完，麻烦有空的话帮忙测试一下，谢谢。
