### ISSUE TITLE
支持@用户功能

### ISSUE THREAD

**Issue by sunlightcs** [88250/lute#116]
在Markdown文本里面，有@用户时，解析成html时候，可以自动带上链接，同时，还可以获取@用户列表，方便后端发送通知

备注：如果@的不是真实用户，后端查询用户表的时候，发现没有这个用户，有接口可以修改不生成链接，就完美了

**Comment by 88250** [comment]
这部分估计只能在 Markdown 处理后再解析 HTML 来做，因为和业务耦合比较多，比如需要实时获取用户名列表。

如果你的系统是 golang 或者 js 实现的话，可以考虑自定义渲染器 `renderText` 函数进行实现。如果需要编辑器端对接的话，建议直接用 Vditor，Vditor 里面处理了自动完成的逻辑。

感谢提议，我关闭了。
