### ISSUE TITLE
支持 JSON 渲染器

### ISSUE THREAD

**Issue by HerbertHe** [88250/lute#120]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

需要给React Native映射一套基于组件和样式的Markdown渲染器，在APP端webview的用户体验并不是很好。在链滴请求过一次直接输出AST，[帖子](https://ld246.com/article/1607760994496)，用内置的自定义renderer的话还是会存在因为类型和默认渲染效果导致的一些问题，在回复中阐述了可能的错误情况。

突然想起来了Vditor自带了一个抽象语法树的调试功能输出树的节点，即`renderEchartsJSON`这个函数，但是调用打印的数据并不完整，又陷入了瓶颈。。。

### 描述最优的解决方案 Describe the optimal solution

期待可以直接输出AST，这样可以供渲染器通过遍历或递归的方式生成组件，eg.

> 引用marked.js的示例

```json
[
  {
    type: "blockquote",
    raw: "> I am using marked.",
    tokens: [
      {
        type: "paragraph",
        raw: "I am using marked.",
        text: "I am using marked.",
        tokens: [
          {
            type: "text",
            raw: "I am using marked.",
            text: "I am using marked."
          }
        ]
      }
    ]
  },
  links: {}
]
```

类似的只需要type、text和可能的子节点即可。

### 描述候选解决方案 Describe the candidate solution

基于lute的`MarkdownStr`方法，前端可以使用正则表达式来提取，然后构建AST，但是效率太低了。

也尝试过使用lute的`HTML2Tree`方法来生成AST，但是js这个函数好像并不被支持emmm

**Comment by 88250** [comment]
估计要稍等一阵子，最近主要精力在思源笔记。如果可能的话可以尝试参考 ECharts 渲染器来实现 PR 谢谢。

**Comment by HerbertHe** [comment]
正在开始尝试写emmm

**Comment by HerbertHe** [comment]
@88250 在参考有些渲染器代码的位置，不是很清楚部分名词实际所指，`renderKramdownBlockIAL`， `renderKramdownSpanIAL` 和 `ial`的属性具体是指？`renderHardBreak`和inlineHTML好像会冲突，默认是inlineHTML，`renderBackslash`不太清楚触发的格式是啥

**Comment by 88250** [comment]
* kramdown ial 请参考 https://kramdown.gettalong.org/syntax.html#inline-attribute-lists
* hardbreak 和 inlinehtml 请参考 GFM 规范，应该不可能会有冲突的
* backslash 是 `\foo`

**Comment by iad12138** [comment]
RenderJSON之后怎么将JSON转回markdown字符串

**Comment by HerbertHe** [comment]
> RenderJSON之后怎么将JSON转回markdown字符串

本来提出这个feat是解决前端渲染问题的，是便于前端来写跨平台的自定义渲染器的。

可以参考一下我基于 markdown-it 写的自定义渲染器 [markmax](https://github.com/HerbertHe/markmax)，也可以转化生成 Vue、React、million.js 的 vdom，直接进行dom的渲染，当时是为了解决 Vditor 大纲依赖第三方库渲染问题的。
