### ISSUE TITLE
js打包的包过大问题

### ISSUE THREAD

**Issue by HerbertHe** [88250/lute#128]
### 描述问题 Describe the problem

使用rollup作为npm打包工具，将`lute.min.js`引入打包，报了一个文件超过500kb的问题

### 期待的结果 Expected result

将可以分开的模块进行分开打包，以降低单个文件的文件大小问题

**Comment by 88250** [comment]
估计拆不了，用的是 [GopherJS](https://github.com/gopherjs/gopherjs) 编译的。
