### ISSUE TITLE
是否可以考虑增加command line使用

### ISSUE THREAD

**Issue by zidoshare** [88250/lute#134]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

我更多的场景是在编辑器更适应的编辑器中编写markdown文本项目，然后想要能够通过命令行格式化、渲染导出

### 描述最优的解决方案 Describe the optimal solution

增加命令行使用

### 描述候选解决方案 Describe the candidate solution

vscode、idea等编辑器插件

### 其他信息 Other information

lute是目前体验最好的中文场景markdown引擎了，而且引擎本身功能已经足够完备，添加命令行功能应该不会很复杂。

**Comment by 88250** [comment]
命令行请单独拉仓库做，不在 Lute 上引入，谢谢。

**Comment by elliotxx** [comment]
@zidoshare 基于 lute 开发了一个命令行 Markdown 格式化工具 [mdfmt](https://github.com/elliotxx/mdfmt)，看下符不符合你的需求

![](https://github.com/elliotxx/mdfmt/raw/master/assets/demo.svg)

**Comment by zidoshare** [comment]
> @zidoshare 基于 lute 开发了一个命令行 Markdown 格式化工具 [mdfmt](https://github.com/elliotxx/mdfmt)，看下符不符合你的需求
> 
> ![](https://github.com/elliotxx/mdfmt/raw/master/assets/demo.svg)

恩恩，写得不错，感谢。
