### ISSUE TITLE
”英文逗号标点在英文和中文之间需要渲染为中文逗号“ 的 feature 好像没有了

### ISSUE THREAD

**Issue by virusdefender** [88250/lute#141]
### 描述问题 Describe the problem

根据 README  和历史的代码 https://github.com/88250/lute/commit/48835114e187d400d5b403e925f6eed25f7e3282 ，是曾经存在过这个功能的，但是在最新的 tag 和 master 上，经过测试，英文标点都没有被替换，而且相关的代码也找不到了。

### 期待的结果 Expected result

英文标点被替换，而且希望支持中文内使用了英文标点的修正。

**Comment by 88250** [comment]
你好，这个功能因为存在一些问题所以最后被移除了。README 改漏了，给你造成困扰，抱歉抱歉。
