### ISSUE TITLE
Text 方法是否应该渲染 NodeCodeSpanContent 的内容？

### ISSUE THREAD

**Issue by 2234839** [88250/lute#146]
### 描述问题 Describe the problem

https://github.com/88250/lute/blob/59cbae4693bc87e6746419dd4065423e1aeda353/ast/node.go#L243

对于如下html,调用 HTML2Text 方法得到的是空字符串
```html
<h2>
  <a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError">
    <code data-type="NodeCodeSpan">ReferenceError</code>
  </a>
</h2>
```

### 期待的结果 Expected result

期望得到 "ReferenceError"

### 版本环境 Version environment
	
github.com/88250/lute v1.7.3-0.20210520091845-ae9b10c9525e

**Comment by 88250** [comment]
这个最好重写一个 Text，内置的这个已有应用里使用的地方比较多，目前不大敢修改。
