### ISSUE TITLE
Vditor 所见即所得模式列表里的行级元素间的空格会被删除

### ISSUE THREAD

**Issue by cweijan** [88250/lute#149]
预期的解析
```
- span **block**
```
实际的解析
```
- span**block**
```
即
1. 当处于列表的情况下, SpinVditorDOM方法会把节点的右侧空白清除掉
2. 由于这个bug严重影响了我的md编写体验, 我debug了一下, 发现是[vditor_wysiwyg.go->281行](https://github.com/88250/lute/blob/c9be96ecd75aca5cb46d5c81d017fff59eaaee9d/vditor_wysiwyg.go#L281)导致的
3. 我现在去掉了这段逻辑重新编译, 这会有什么问题吗.

**Comment by 88250** [comment]
问题已经确认，稍后修复，谢谢。
