### ISSUE TITLE
请问怎么不启用自动识别链接？或者说不识别一些自定义的一些网址

### ISSUE THREAD

**Issue by LolitaSquad** [88250/lute#150]
现在默认是会自动识别链接并转成A标签 会把 `https://duckduckgo.com`转成  `<p><a href="https://www.duckduckgo.com">https://www.duckduckgo.com</a></p>
`
 但是不想要自动识别某些特定的网址   或者  所有网址都不自动识别  需要怎么实现呢

**Comment by 88250** [comment]
关闭解析选项 `GFMAutoLink`。
