### ISSUE TITLE
Table 紧跟的上一行不是空行时，SpinVditorSVDOM 会将整个表格过滤掉

### ISSUE THREAD

**Issue by bluishoul** [88250/lute#158]
### 描述问题 Describe the problem

RT

#### 复现步骤：

1. 访问 https://ld246.com/guide/markdown
2. 分屏预览模式下，清空编辑器内容
3. 点击 “表格” icon 插入默认表格
4. 在表格前输入 `a` 或其他字符
5. 表格内容被过滤

#### 原因分析

经过本地调试，发现紧接着的内容（`a`）和表格会被识别成一个 Paragraph，然后 `table.go#parseTable0` 时 `aligns := context.parseTableDelimRow(lex.TrimWhitespace(lines[1]))` 识别表格第二行失败导致

#### 解决办法

本地尝试将 `table.go#parseTable` 逻辑改成先识别表格开始行，然后分离表格和上一行的内容，然后再对表格进行处理，但是似乎不可行，问题可能出在更上层的 Paragraph 解析逻辑。

### 期待的结果 Expected result

1. Table 内容不被过滤，或者
2. 类似 cmark-gfm 一样能够[识别 Table 前不是空格](https://github.com/github/cmark-gfm/pull/154)的情况
  test case: https://github.com/github/cmark-gfm/blob/master/test/extensions.txt#L475-L500

### 截屏或录像 Screenshot or video

![2021-10-09 12 44 35](https://user-images.githubusercontent.com/1284728/136644456-7b02f2c5-79ba-4ab4-b5c4-4fb9b6838bcb.gif)

### 版本环境 Version environment

* 版本 Version：master/dev
* 操作系统 Operating system：macOS
* 浏览器（如果使用）Browser (if used)： Chrome

**Comment by bluishoul** [comment]
@88250 应用此修复后（[最新的 lute.min.js](https://github.com/88250/lute/blob/96ab6d06f0504cf9132be1bb3f17fac591974fcc/javascript/lute.min.js )），本地测试发现会自动将**表格上一行内容**和**表格**中间加上换行，如果是单纯的处理表格和上一行其他内容时这没问题，但是如果如下图在表格内插入空行，就没法直接删掉该空行：

![2021-10-13 15 19 42](https://user-images.githubusercontent.com/1284728/137086033-c9cc1a33-7f06-4420-809a-376ddbd1ef92.gif)

**Comment by 88250** [comment]
@bluishoul spin 时会做一次格式化，这个机制调整不了。
