### ISSUE TITLE
支持导出 VNode

### ISSUE THREAD

**Issue by HerbertHe** [88250/lute#167]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

Vditor 的 sv 模式存在卡顿的性能问题，相比于更新所有的渲染重绘 HTML DOM 导致大量的性能损耗，前端更常见使用 VDOM 解决大量 DOM 更改的渲染问题，诸如 React、Vue 等均在 VDOM 上花费心力进行 Diff，以求真实 DOM 的最小改动。

### 描述最优的解决方案 Describe the optimal solution

参考开源项目 [Million](https://github.com/aidenybai/million)，提供了开箱即用的 VDOM 支持。HTML DOM 转化为 VNode 需要一定的时间，不如直接编译导出 VNode 然后扔给第三方开源项目进行处理，根据改动渲染真实环境下的 DOM 以实现最小改动（与RenderJSON 类似）。

支持 API `lute.exportVNode`

**Comment by 88250** [comment]
就目前来说没有这个计划，如果需要的话可 fork 改造，感谢提议。
