### ISSUE TITLE
请问如何自定义GFMAutoLink的渲染样式

### ISSUE THREAD

**Issue by Yakumo-Yukari** [88250/lute#169]
当前的渲染
< p > <  a href="https://cn.bing.com/ rel="external nofollow" target="_blank" title="https://cn.bing.com/">https://cn.bing.com/</ a >< / p >
< p > 带内容呢 <   a href="https://www.pixilart.com" rel="external nofollow" target="_blank" title="https://www.pixilart.com/"> 
 https://www.pixilart.com/  </   a > < / p >

如果想给他们加上class 可以行吗？

还有就是是否可以指定某个或多个特殊链接不渲染呢？

不知道上述的功能是否可行  谢谢

**Comment by 88250** [comment]
可以自定义渲染器的，请参考 render 包。
