### ISSUE TITLE
请问这个tip是后端渲染问题吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [88250/lute#170]
![1 0](https://user-images.githubusercontent.com/12076232/167277459-27275f1a-1862-406b-8d8f-ae123c31d095.png)
![1 1](https://user-images.githubusercontent.com/12076232/167277461-662b0248-ce65-4023-8cdd-079a04a8d1b4.png)

![22](https://user-images.githubusercontent.com/12076232/167277571-07e63de2-0885-40c7-b29e-8285a5f1dd6e.png)
![33](https://user-images.githubusercontent.com/12076232/167277572-bba2e386-6620-4c86-b695-adda8aa0b2de.png)

::: warning
在此输入内容
:::

 在编辑器预览里可以正常显示 但是渲染后就不能正常显示了  会被直接换成p标签

**Comment by 88250** [comment]
这个不是标准 Markdown 语法，Lute 没有进行实现。

**Comment by Yakumo-Yukari** [comment]
> 这个不是标准 Markdown 语法，Lute 没有进行实现。



> 这个不是标准 Markdown 语法，Lute 没有进行实现。

后面会支持吗？

**Comment by 88250** [comment]
暂时没有计划，可以试下自己改改代码看。
