### ISSUE TITLE
为什么引入之后没反应呢

### ISSUE THREAD

**Issue by Li-Juan-Siwei** [88250/lute#173]
<script src="./lute.min.js"></script>
    <div id="content"></div>
    <script>
      var luteEngine = lute.New();
      document.getElementById("content").innerHTML  = luteEngine.MarkdownStr("demo", "**Lute** - A structured markdown engine.");
    </script>
引入lute.min.js后无法渲染成功.,但使用marked模块里面的marked.min.js就可以把markdown渲染成html

**Comment by 88250** [comment]
请参考示例代码 https://github.com/88250/lute/blob/master/javascript/lute.html
