### ISSUE TITLE
脚注支持 Base URL 设置

### ISSUE THREAD

**Issue by myml** [88250/lute#176]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在使用单页面应用，设置了网页的base href后，脚注渲染的锚点链接指向base href而不是当前页面url。

### 描述最优的解决方案 Describe the optimal solution
脚注支持使用LinkBase选项设置基础路径。

### 描述候选解决方案 Describe the candidate solution
添加新的FootnotesBase选项（类似LinkBase），用于设置脚注的链接路径。

### 其他信息 Other information
如果同意方案的话，我可以来进行具体实现。

**Comment by 88250** [comment]
感谢提议，欢迎贡献。
