### ISSUE TITLE
a 标签怎么渲染 target="_blank" 属性？

### ISSUE THREAD

**Issue by leehomlee** [88250/lute#179]
### 如题

````````markdown
### 三级标题
测试
[百度](https://www.baidu.com)
````````

### 期待的结果 Expected result

<a href="https://www.baidu.com" target="_blank">百度</a>

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
需要自行扩展渲染器。

**Comment by leehomlee** [comment]
可以给一个渲染加上 target 属性的示例代码啵[狗头]

**Comment by leehomlee** [comment]
算了，没折腾了，最后通过 正则 加上的 target 属性
