### ISSUE TITLE
列表渲染异常

### ISSUE THREAD

**Issue by gaoyoubo** [88250/lute#181]
### 描述问题 Describe the problem

Markdown原文件如下图：
![image](https://user-images.githubusercontent.com/2127168/188418607-6f62d2b5-7a0c-4825-b449-3f14b20322e9.png)

### 期待的结果 Expected result

期待结果如下：

![image](https://user-images.githubusercontent.com/2127168/188418791-83652359-8923-41fe-ad11-55cc1a8f43a8.png)

而实际结果却是：

![image](https://user-images.githubusercontent.com/2127168/188418920-a7dba306-6bc2-4974-96cd-91e575037be4.png)

### 版本环境 Version environment

1.7.3

**Comment by 88250** [comment]
麻烦提供一下调用的函数和输入参数。

**Comment by gaoyoubo** [comment]
> 麻烦提供一下调用的函数和输入参数。

```go
engine := lute.New(func(lute *lute.Lute) {
	lute.SetToC(true)
	lute.SetSanitize(true)
	lute.SetGFMTaskListItem(true)
})
engine.MarkdownStr("", markdownStr)
```

**Comment by 88250** [comment]
我这里测试：

```markdown
1. foo

bar

2. baz
```

输出的 HTML：

```
<ol>
<li>foo</li>
</ol>
<p>bar</p>
<ol start="2">
<li>baz</li>
</ol>
```

似乎没有发现问题。

**Comment by 88250** [comment]
测试用例见 https://github.com/88250/lute/blob/master/test/debug_test.go 文件中的 `64` 号用例。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by gaoyoubo** [comment]
@88250 感谢， 是我自己的问题。 我再生成markdown内容之后对html内容做了一遍过滤，没有将start属性放开。

bluemonday.UGCPolicy() 
ugcProtection.AllowAttrs("class").OnElements("code")
