### ISSUE TITLE
Please add support for wikilinks

### ISSUE THREAD

**Issue by 64bits** [88250/lute#182]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

Using vditor in VS code to make a Zettelkasten style system.

### 描述最优的解决方案 Describe the optimal solution

Markdown links are supported in various ways, here is an [example](https://meta.m.wikimedia.org/wiki/Help:Link) from Wikipedia. It would be ideal if the links support titles (different text) and anchor links.

### 描述候选解决方案 Describe the candidate solution

When parsing brackets, double brackets can be special cased as a possible wikilink, and the close bracket parser can check for this special case and create a link without requiring parentheses.

### 其他信息 Other information

Addressing this issue would also enable https://github.com/Vanessa219/vditor/issues/789

**Comment by 64bits** [comment]
I have a change that supports this here: https://github.com/88250/lute/commit/ba1db3e2610daf2542ea973841f2558c54208e0f, however it breaks spec516.

**Comment by 88250** [comment]
Hi, thanks for reading and improving Lute. But we don't have time for detailed review and revision at present. If you need this function, please fork to modify it. Thank you for your understanding.

**Comment by MacWeber** [comment]
@88250 I see you later commented on a related issue:

        Vditor just an editor rather than an application, it can not read another file content for rendering. But I think the syntax element `[[wiklink]]` should be implemented.

_Originally posted by @88250 in https://github.com/Vanessa219/vditor/issues/789#issuecomment-714114627_
      

This is an important feature in many apps such as [Obsidian](https://obsidian.md/), [Roam Research](https://roamresearch.com/) and others. Adding this functionality would let [Foam](https://github.com/foambubble/foam) render proper wikilinks. So, I'm wondering if you could consider to re-open this issue :pray:
