### ISSUE TITLE
vite import导入，打包报错

### ISSUE THREAD

**Issue by webpon** [88250/lute#183]
![image](https://user-images.githubusercontent.com/50807258/210129144-e28023d9-26d8-468e-984d-1bdc1358e60e.png)
最新版本
![image](https://user-images.githubusercontent.com/50807258/210129159-0a4d6c67-b137-4ccc-b789-7c27a2de5926.png)
这个是语法或者格式报错的吗

**Comment by 88250** [comment]
这个我不太清楚，应该不是 Lute 项目的问题。

**Comment by webpon** [comment]
有提供npm包或者支持import的包吗

**Comment by 88250** [comment]
Lute 没有提供单独的 NPM 包，只有编译好的 lute.min.js

**Comment by webpon** [comment]
想进行二次开发真的太难了

**Comment by webpon** [comment]
能出一个js不丑hua化的文件吗
![image](https://user-images.githubusercontent.com/50807258/210129941-c8ce45f0-0363-45a6-80be-0b8b03e9ef31.png)

**Comment by webpon** [comment]
问题终于解决了，我二次修改是为了处理一个问题，就是添加图片前缀，lute会把base64的图片也加上前缀，所以我做了base64的排除，希望在后续版本能优化这一点
