### ISSUE TITLE
1.7.3 及以上版本的术语拼写修正失效了

### ISSUE THREAD

**Issue by zidoshare** [88250/lute#185]
### 描述问题 Describe the problem

1.7.3 及以上版本的术语拼写修正失效了

```go
package main

import (
	"fmt"

	"github.com/88250/lute"
)

func main() {
	fmt.Println(lute.New(func(engine *lute.Lute) {
		engine.RenderOptions.AutoSpace = true
		engine.RenderOptions.FixTermTypo = true
	}).FormatStr("test", "这是一个 github 测试"))
}
```

### 期待的结果 Expected result

```
这是一个 GitHub 测试
```

经过测试，在 1.7.3 以下版本正常，以上无法修正，得出的结果是：

```
这是一个 github 测试
```

经过 debug ，看起来是 token 生成有问题，拿到的是段而不是块。
<img width="907" alt="image" src="https://user-images.githubusercontent.com/11310504/218682534-7a92ee10-6b06-4b2a-b375-d2deba7916f3.png">

**Comment by 88250** [comment]
我这里测试正常，请参考上面提交的测试用例。
