### ISSUE TITLE
关于nuxt3报错“Cannot convert undefined or null to object”

### ISSUE THREAD

**Issue by lz6060788** [88250/lute#191]
### 描述问题 Describe the problem

nuxt3使用Lute.min.js进行markdown文本解析时，产生了一个报错，具体报错点下方存在截图

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/98386138/226622618-a43766d7-b287-4948-b705-56a7053c9d8b.png)
在客户端渲染时，$global.process为undefined，上方if处直接return结束
而我尝试使用服务端渲染时，k为一个结构体，但没有env属性，导致断点处获取其key时抛出错误。

### 版本环境 Version environment

* 版本 Version：3.9.1
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：chrome
* Nuxt3.2.0

**Comment by 88250** [comment]
可能需要提供更多信息才好定位问题，比如：

* 输入的 Markdown 文本
* Lute 参数选项

**Comment by lz6060788** [comment]
和markdown文本应该没什么关系，我上传了一个能够复现的最小化项目，[代码仓库链接](https://github.com/lz6060788/nuxt-vditor)

**Comment by 88250** [comment]
非常抱歉，我目前没有时间看这个问题……

**Comment by lz6060788** [comment]
没事，我先采取其他方案避免这个问题，后续这个问题查到原因我再回复

**Comment by lz6060788** [comment]
这个问题我看主要引起的原因是由于nuxt这个环境下，它给window设置了属性window.process: { client: boolean, server: boolean }，而普通浏览器环境下的window不存在该属性。Lute引擎代码中有三四处判断了$global(window).process === 'undefined'，这在nuxt环境下是不准确的，自行调试在各判断处补充为 $global.process.client || $global.process === 'undefined'后不再出现报错，具体你们可以参考一下看修复方案需要咋整

**Comment by 88250** [comment]
请看下是不是类似这个地方：

https://github.com/gopherjs/gopherjs/blob/df0fbb1be49872e28d6cf1415d3f8ffc8bd76c90/compiler/prelude/prelude.go#L75

**Comment by lz6060788** [comment]
对没错，就是类似于这样的地方，不过此处并没有产生报错，我也没有做修改，下面有几处产生的报错的和这里是一样的。我修改的是lute.min.js，截图放附件了






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "88250/lute"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [88250/lute] 关于nuxt3报错“Cannot convert undefined or null to object” (Issue #191)





 
请看下是不是类似这个地方：
 
https://github.com/gopherjs/gopherjs/blob/df0fbb1be49872e28d6cf1415d3f8ffc8bd76c90/compiler/prelude/prelude.go#L75

**Comment by FrankOldmoon** [comment]
> 对没错，就是类似于这样的地方，不过此处并没有产生报错，我也没有做修改，下面有几处产生的报错的和这里是一样的。我修改的是lute.min.js，截图放附件了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "88250/lute" ***@***.***&gt;; 发送时间:&nbsp;2023年3月28日(星期二) 中午11:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [88250/lute] 关于nuxt3报错“Cannot convert undefined or null to object” (Issue #191) 请看下是不是类似这个地方： https://github.com/gopherjs/gopherjs/blob/df0fbb1be49872e28d6cf1415d3f8ffc8bd76c90/compiler/prelude/prelude.go#L75 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问修复了吗？我现在也遇到了这个问题，想在nuxt3中实现SSR渲染。

**Comment by terwer** [comment]
大概37行，加一个判断就行

```js
if(!i){return;}
```

我看根源是 process.argv是undefined的时候没判断导致

源码

```js
h=$global.process;if(!(h===undefined)){i=h.argv;$pkg.Args=$makeSlice(FK,($parseInt(i.length)-1>>0));
```

修改之后

```js
h=$global.process;if(!(h===undefined)){i=h.argv;if(!i){return;}$pkg.Args=$makeSlice(FK,($parseInt(i.length)-1>>0));
```

改完之后可用 

```js
const lute=Lute.New();const html = lute.MarkdownStr("", "# hello");html
```

![image](https://user-images.githubusercontent.com/3259282/232981569-f325fe40-7ac8-4431-bae2-786703cad9f1.png)

另外我是直接引用的，如下：

```ts
// nuxt.config.ts
const staticV = "202304191333"

app: {
  head: {
    script: [
      {
        src: appBase + "lib/lute/lute-1.7.5-20230410.min.js?v=" + staticV,
        body: true,
      },
    ],
  },
},
```
我这是ssr=fasle的spa方案。ssr的话可能还得踩坑

**Comment by lz6060788** [comment]
个人实践下来，在nuxt3框架下不建议使用这个渲染引擎，首先他在浏览器环境下判断window.process属性，将浏览器环境误判断了为了node环境，目前没有什么很好的办法，当前采取的方案是修改源码，并迁移cdn；其次在服务器端也存在问题，nuxt3的服务端为nitro，是采用的es6规范运行的，而lute.min.js本身为commonjs模块，使用上不兼容，强行引入将导致build失败，可能外置一个node服务进行md解析会好一点。

后续可能会尝试在服务器端解析时采用别的markdown引擎转换成html，在浏览器端再使用vditor的静态方法对解析的html文本进行二次渲染，不过尚未比较如marked和lute两者在将markdown转换成html时会有什么差别。

**Comment by lz6060788** [comment]
> 个人实践下来，在nuxt3框架下不建议使用这个渲染引擎，首先他在浏览器环境下判断window.process属性，将浏览器环境误判断了为了node环境，目前没有什么很好的办法，当前采取的方案是修改源码，并迁移cdn；其次在服务器端也存在问题，nuxt3的服务端为nitro，是采用的es6规范运行的，而lute.min.js本身为commonjs模块，使用上不兼容，强行引入将导致build失败，可能外置一个node服务进行md解析会好一点。
> 
> 后续可能会尝试在服务器端解析时采用别的markdown引擎转换成html，在浏览器端再使用vditor的静态方法对解析的html文本进行二次渲染，不过尚未比较如marked和lute两者在将markdown转换成html时会有什么差别。

纠正一下，nuxt3生产环境应该不会被误判，它不具备window.process属性

**Comment by terwer** [comment]
ssr已验证，我上面的修复版，可以完美运行。

https://github.com/terwer/zhi/blob/dev/apps/zhi-server-vue3-ssr/public/lib/lute/lute-1.7.5-20230410.min.cjs

可以看看我的：https://github.com/terwer/zhi/blob/dev/apps/zhi-server-vue3-ssr/src/server/index.ts#L86

服务端效果

![image](https://user-images.githubusercontent.com/3259282/234090792-04c32233-0380-4223-8cf9-db74d5fc3843.png)


客户端效果

![image](https://user-images.githubusercontent.com/3259282/234090851-e1ca49ab-70b1-4d8e-9ea1-5d8d1904299f.png)

**Comment by 88250** [comment]
这个问题我们关闭了，目前没有办法从根源上解决，感谢各位讨论。
