### ISSUE TITLE
针对 XSS 处理的架构改进

### ISSUE THREAD

**Issue by Chenrt-ggx** [88250/lute#197]
目前，lute 被发现**多种** xss 漏洞，如下：

- [未过滤 iframe 的 srcdoc 字段](https://github.com/88250/lute/issues/192)。
- [伪协议过滤可空白字符绕过](https://github.com/88250/lute/issues/193)。
- [未过滤链接中的伪协议](https://github.com/88250/lute/issues/194)。
- [未过滤 meta 标签](https://github.com/88250/lute/issues/195)。
- [未过滤 form 中的 formaction 字段](https://github.com/88250/lute/issues/196)。

这表明，lute 在 xss 处理上**可能存在架构设计问题**、**可能存在其它 xss 注入漏洞**。因而，个人认为：

- 如果 lute 希望进行完善的 xss 过滤，建议重新设计并实现 xss 过滤或使用现有的过滤库。
- 如果 lute 希望尽可能进行 xss 过滤，请不要提供 SetSanitize 这一具有**强烈误导性**的功能，参考 marked。

<img width="560" alt="" src="https://github.com/88250/lute/assets/64241518/7dabebab-ba8c-4fc2-bbd0-65c466226ce0">

**Comment by 88250** [comment]
我们希望 Lute 能够尽可能地进行 XSS 过滤，稍后会在 `SetSanitize` 函数文档上进行说明，非常感谢。

关联 https://github.com/88250/lute/issues/51

```go
// SetSanitize 设置为 true 时表示对输出进行 XSS 过滤。
// 注意：Lute 目前的实现存在一些漏洞，请不要依赖它来防御 XSS 攻击。
func (lute *Lute) SetSanitize(b bool) {
	lute.RenderOptions.Sanitize = b
}
```
