### ISSUE TITLE
链接含下划线时，自动添加转义斜线问题

### ISSUE THREAD

**Issue by FantasticPornTaiQiang** [88250/lute#201]
### 描述问题 Describe the problem

vditor实例调用html2md方法，调用如下：

```
vditor.html2md('&lt;img src="a_1.png" &gt;')
```

### 实际结果

`<img src="a\_1.png" >`

图片的src中，下划线（_）前多了一个反斜杠。

### 预期结果

`<img src="a_1.png" >`

按道理说图片路径应该允许出现下划线，不需要转义。

**Comment by 88250** [comment]
经测试，传入的 `&lt;img src="a_1.png" &gt;` 会被作为文本，所以加了转义。

**Comment by 88250** [comment]
请参考 https://github.com/88250/lute/commit/e9840a3d1464a1d27b4ee23d5067a3adadd9eeae 中补充的测试用例。
