### ISSUE TITLE
Md2BlockDOM 无法正确解析"$1$"

### ISSUE THREAD

**Issue by duanxianpi** [88250/lute#205]
### 描述问题 Describe the problem

Md2BlockDOM 函数解析有问题, "$1$" 无法被正确转为 math div

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here

$1$
````````

### 截屏或录像 Screenshot or video
![image](https://github.com/88250/lute/assets/97914968/e537c187-3b57-486a-ad08-28dbb334add6)

### 版本环境 Version environment

* 版本 Version：1.7.6
* 操作系统 Operating system：Windows 11
* 浏览器（如果使用）Browser (if used)：Chrome 125.0.6422.142 (Official Build) (64-bit)

**Comment by 88250** [comment]
需要打开解析选项  InlineMathAllowDigitAfterOpenMarker
