### ISSUE TITLE
新增 `protyle-custom` 类别：在构建 AST 的时候，直接忽略内部的内容

### ISSUE THREAD

**Issue by frostime** [88250/lute#206]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

改 protyle 内部元素的需求其实在开发者社区里面由来已久，比如 VV 的增强插件里就有段落锁功能；我也一直想给 callout 插入一个折叠按钮。

但是由于担心会误伤 protyle 结构导致内容丢失，所以大家对这个操作是有疑虑的——比如 VV 的段落锁功能，存在有时候会把块变成 html 块的 bug。

如果增加这个逻辑，也许一定程度上解决这个问题。

### 之前的讨论

之前私下里我咨询过是不是自定义在 protyle 中插入的元素只要 class 名称命名为含有 `__copy` 或者 `protyle-action` 这些字符串的名称就不会被视为文档内容，从而**避免错误地修改文档内容**。

在得到了肯定的回答之后，我又看了一下 protyle.go 觉得应该没问题，因为我看到的所有涉及到解析 BlockDOM 的函数，最后都会来到 genASTByBlockDOM 函数中。

[https://github.com/88250/lute/blob/v1.7.6/protyle.go#L680](https://github.com/88250/lute/blob/v1.7.6/protyle.go#L680)

### 描述最优的解决方案 Describe the optimal solution

这里，我希望能不需要搭原本已有的处理逻辑的顺风车（毕竟也提到，<u>以后可能会改动也说不定</u>），而是单独开一个约定：例如可以规定，所有 className 为 `protyle-custom`（也可以是别的）的 element 都不参与 AST 的构建。

这个方案具体到代码实现中也很简单：在 `genASTByBlockDOM` 开头插入**三行代码**就行了。

```go
class := util.DomAttrValue(n, "class")
//三行代码
if "protyle-custom" == class {
	return
}
```

**Comment by Wetoria** [comment]
我这个评论是补充一个我遇到的细节情况，f佬要是有精力的话，可以试一下。

段落锁其实不是插入了自定义的dom，而是直接把 contenteditable 改成了 false。

在这种情况下，如果出现了该段落参与修改的情况下，就会解析成 html 内容。

在下面这个列表项里，假如段落1改成了 false，段落2还是可以编辑的。这个时候继续新增段落3并且输入内容的话，因为段落1是false，就会出现段落1变成html块。
<img width="552" alt="image" src="https://github.com/user-attachments/assets/7c0db015-2cb8-470a-a06f-04f09743442c">


https://github.com/user-attachments/assets/c360745c-abf6-4ee2-a595-95ddf0486e33

**Comment by 88250** [comment]
@frostime 能 PR 的话来一发，谢谢。
