### ISSUE TITLE
how to build lute.min.js

### ISSUE THREAD

**Issue by jakekwak** [88250/lute#26]
I want to build the `lute.min.js`. 

![lute](https://user-images.githubusercontent.com/15811943/75120852-5914d300-5654-11ea-88f6-1b844dd47403.PNG)

**Comment by 88250** [comment]
Try to put source code on $GOPATH, like this 
![image](https://user-images.githubusercontent.com/873584/75124584-2a960700-56eb-11ea-8fd0-6a6b29fc4693.png)

**Comment by jakekwak** [comment]
thanks.
