### ISSUE TITLE
lists preview return

### ISSUE THREAD

**Issue by jakekwak** [88250/lute#56]
```
* test

+ test

- test

1. test

1) test

* [ ] test

+ [ ] test

- [ ] test
```
Current return value
![Screen Shot 2020-04-16 at 11 37 17 AM](https://user-images.githubusercontent.com/15811943/79482828-f9450380-7fd6-11ea-9018-a79572bd8d51.png)

If possible, please change to the below(or some attribute like `*`, `+`, `-`, `1.`, `1)`), It means we can make the differnet preview style using `list-style-type`
```
<ul class="asterisk">
    <li>test</li>
</ul>
<ul class="plus">
    <li>test</li>
</ul>
<ul class="minus">
    <li></li>
</ul>
<ol class="period">
    <li>test</li>
</ol>
<ol class="Parenthesis">
    <lit>test</lit>
</ol>
<ul class="asterisk">
    <li class="vditor-task">test</li>
</ul>
<ul class="plus">
    <li class="vditor-task">test</li>
</ul>
<ul class="minus">
    <li class="vditor-task">test</li>
</ul>
```

**Comment by 88250** [comment]
I think it has been implemented in issue  #48 https://github.com/88250/lute/commit/61b190a2664f9c7548463b78cc883227f67e8525

```go
func (lute *Lute) SetRenderListMarker(b bool) {
	lute.RenderListMarker = b
}
```

Try to set it with `true` and check out the render result.

**Comment by jakekwak** [comment]
How do I set `true` at Vditor editor?

**Comment by Vanessa219** [comment]
vditor.vditor.lute.SetRenderListMarker

**Comment by jakekwak** [comment]
@88250 @Vanessa219 Thanks
