### ISSUE TITLE
Vditor 支持 - 任务列表项的优化操作问题

### ISSUE THREAD

**Issue by shuanzia** [88250/lute#65]
https://github.com/88250/lute/blob/20957f8cb2f7d81601822187d53c8c325b831c5e/parse/paragraph.go#L64

您好，在阅读源代码时，发现一个问题，如题所述。
源代码片段：
```
        closeBracket := bytes.IndexByte(tokens, len(lex.ItemCloseBracket))
        ...
        } else if bytes.HasPrefix(tokens[closeBracket:], []byte(Caret)) {
        ...
```
因为上面closeBracket为ItemCloseBracket所在的下标。如果要想判断Caret的bytes是否在ItemCloseBracket之后的第一个位置，那么下标应该是closeBracket加1。

如下，调整为：
```
        ...
        } else if bytes.HasPrefix(tokens[closeBracket+1:], []byte(Caret)) {
        ...
```

如果我有理解不全面的问题，可以关闭或者删除该issue，感谢。

**Comment by 88250** [comment]
感谢反馈，是一个 bug，稍后修复。

**Comment by 88250** [comment]
如果后续还有发现其他问题，欢迎直接 PR 修复，谢谢！

**Comment by shuanzia** [comment]
> 如果后续还有发现其他问题，欢迎直接 PR 修复，谢谢！

好的。

最初是通过网络发现这个库，也是学习的态度在阅读，没有特意针对挑刺的意思，望理解哈

**Comment by 88250** [comment]
放心，我不会认为是别人在挑刺，正因为有大家的建议才让 Lute 变得更好，这也是开源的意义 🙏
