### ISSUE TITLE
[Feature Request] 可选关闭 term_typographer

### ISSUE THREAD

**Issue by SukkaW** [88250/lute#68]
### 你在什么场景下需要该功能？

term_typographer 改善了文本的准确性，但是可能会影响性能。提供一个选项禁用 term_typographer 有可能会加快渲染速度。

### 描述可能的解决方案

在使用 `lute.MarkdownStr()` 渲染时传入相关配置。

### 描述你认为的候选方案

新增 `lute.disableTermTypographer()` 方法。

### 其他信息

更新 benchmark，新增「BenchmarkLute-with-term_typographer-disabled」。

**Comment by 88250** [comment]
你好，Options 的 `FixTermTypo` 配置选项就是用来控制这个的，js 端可使用 `SetFixTermTypo` 函数对其进行设置。
