### ISSUE TITLE
调用 HTML2Markdown 转换 行内代码 <code> 内容末尾内容丢失问题

### ISSUE THREAD

**Issue by degbug** [88250/lute#71]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

将`<code>name</code>`或者`<code>getValue</code>`，`<code>Method</code>`等，最后的字母会丢失，烦请看看什么问题，谢谢！

代码如下：
```go
package main

import (
	"fmt"

	"github.com/88250/lute"
)

func main() {
	luteEngine := lute.New() // GFM support and Chinese context optimization have been enabled by default
	md, _ := luteEngine.HTML2Markdown(`
	<p>测试 <code>nameme</code> 属性。调用  <code>getValue</code> 时 <code>Method</code></p>
	`)
	fmt.Println(md)
	// <p><strong>Lute</strong> - A structured Markdown engine.</p>
}

```

输出的结果如下：
```
测试 `namem` 属性。调用  `getValu` 时 `Meth`
```

### 期待的结果

code中的内容不要丢失，猜测可能是术语拼写修正的问题

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。
![image](https://user-images.githubusercontent.com/11486075/84519021-1874be80-ad04-11ea-8bb2-277d53d74f82.png)

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
感谢反馈，已经定位到问题，稍后修复。

请关注新版本发布，谢谢。
