### ISSUE TITLE
支持自定义解析器

### ISSUE THREAD

**Issue by 88250** [88250/lute#75]
目前已经支持自定义渲染器，但是有的业务场景需要自定义扩展语法，如果能支持自定义解析器的话会比较方便。

* 需要重构现有解析实现，分为块级解析器、行级解析器，并支持定义优先级
* 需要支持节点类型扩展
* 需要支持 JS 端扩展解析器定义

**Comment by aquarius-wing** [comment]
你好，请问一下这一issue有最新进展吗？如果需要修改源码新增扩展语法的话，是不是只改Go语言相关代码就可以了？

**Comment by 88250** [comment]
@Wing-Lo 目前没有进展，因为似乎需求场景不多。现在要用的话只能改 Go 代码。

**Comment by aquarius-wing** [comment]
好的，谢谢解答

**Comment by xmflswood** [comment]
这一块如果能支持的话，可以让社区开发者以插件的形式贡献出各种小工具，还是值得期待的

**Comment by 88250** [comment]
暂时不考虑了，分身乏术，如果其他开发者有空的话可以探讨一下，谢谢。
