### ISSUE TITLE
md渲染图片后span节点添加data-type

### ISSUE THREAD

**Issue by angleshe** [88250/lute#81]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

md渲染图片后span节点添加data-type

````````markdown
![image](....)
````````

### 期待的结果

\<span class="vditor-ir__node" data-type="img">

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

![image](https://user-images.githubusercontent.com/25807379/88771455-dddebc80-d1b1-11ea-9a4b-e196a794bed7.png)
### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
可能是加漏了，稍后我们确认一下，感谢反馈。

@Vanessa219

**Comment by 88250** [comment]
已经确认没问题，下个版本加。
