### ISSUE TITLE
支持内容块引用语法

### ISSUE THREAD

**Issue by 88250** [88250/lute#82]
## 需求

https://github.com/88250/liandi/issues/87

## 实现

* [x] 引入新的语法 `((id "text"))`，节点类型 `BlockRef`、`BlockRefID`、`BlockRefSpace`、`BlockRefText`
* [x] 行级解析主循环中加入 `(` 分支处理
* [x] 增加解析选项 `BlockRef`，默认关闭
* [x] 暂时仅在 `VditorIRBlockRenderer` 中新增渲染函数

**Comment by 2501224066** [comment]
nb
