### ISSUE TITLE
支持 ==Mark== 标记语法

### ISSUE THREAD

**Issue by 88250** [88250/lute#84]
使用开关 `Mark`，默认关闭。

**Comment by 88250** [comment]
https://github.com/Vanessa219/vditor/issues/719

**Comment by jakekwak** [comment]
I think this is not GFM spec. 
if not, I want to suggest the new spec.

For font size, font, text color, background color
[]{:.intro.red.fontsize#id.class} 

For paragraph
{:.center}

This is not the standard, but when you support this kind of syntax,  The Vditor seems to be competitive with other wysiwyg editors.(froala, ckeditor etc.)

You can also export as standard GFM spec.

**Comment by 88250** [comment]
@jakekwak Yes, we will gradually introduce more extended syntax.

**Comment by jakekwak** [comment]
@88250 Here is some comparison chart
<img width="966" alt="Screen Shot 2020-08-17 at 7 58 24 PM" src="https://user-images.githubusercontent.com/15811943/90458514-3a077300-e0c4-11ea-9a55-f18f10bd1db4.png">
<img width="967" alt="Screen Shot 2020-08-17 at 7 58 55 PM" src="https://user-images.githubusercontent.com/15811943/90458519-3d9afa00-e0c4-11ea-9a5f-1f7fbe71b983.png">
