### ISSUE TITLE
引入链接强制前缀 `linkPrefix`

### ISSUE THREAD

**Issue by ghost** [88250/lute#94]
### 描述问题

在图片链接是绝对路径的时候, linkBase失效了, 是相对路径就没问题.
linkBase:
![image](https://user-images.githubusercontent.com/37654563/96062683-e0a3a080-0ec8-11eb-9a49-1f78c1bf9c79.png)
渲染结果
![image](https://user-images.githubusercontent.com/37654563/96062722-fb761500-0ec8-11eb-8dea-49ca27a81a6c.png)
![image](https://user-images.githubusercontent.com/37654563/96062731-02048c80-0ec9-11eb-90d5-1cdde3bf11dd.png)

我希望是这样的:
```html
<img src="vscode-webview-resource://963f4748-5eb6-47b5-99b6-5390c18dd8d6/file///C:/Users/tobiastao/code/vscode-md-test/1602725319564.jpeg" alt="1602725319564.jpeg">
```

**Comment by 88250** [comment]
你好，linkBase 的设计用意：

https://github.com/88250/lute/blob/8953b2590548006dc45feeaa061e3e231a4dced3/parse/parse.go#L278

对于需要前缀的需求我们需要再引入一个 linkPrefix 来实现，即只要配置该选项就会在目标链接内容前固定加上配置的前缀值。稍后就进行实现，谢谢。

**Comment by 88250** [comment]
```go
// LinkPrefix 设置连接、图片的路径前缀。一旦设置该值，链接渲染将强制添加该值作为链接前缀，这有别于 LinkBase。
// 比如 LinkPrefix 设置为 http://domain.com，对于使用绝对路径的 ![foo](/local/path/bar.png) 则渲染为 <img src="http://domain.com/local/path/bar.png" alt="foo" />；
// 在 LinkBase 和 LinkPrefix 同时设置的情况下，会先处理 LinkBase 逻辑，最后再在 LinkBase 处理结果上加上 LinkPrefix。
LinkPrefix string
```

**Comment by ghost** [comment]
谢谢D大 😄
