### ISSUE TITLE
使用 lute.MarkdownStr("", md_str) 得到的结果里面有id 该怎么处理

### ISSUE THREAD

**Issue by 2234839** [88250/lute#98]
### 描述问题

使用 lute.MarkdownStr("", md_str) 得到的结果里面有id

### 截屏或录像

![图片](https://user-images.githubusercontent.com/28727933/98093803-5f399f80-1ec3-11eb-9bfd-b85e3bf5ab4d.png)

**Comment by 88250** [comment]
请把 lute 实例上的 `KramdownIAL` 设置为 `true` 后再调用试试，谢谢。

**Comment by 2234839** [comment]
解决方案
![图片](https://user-images.githubusercontent.com/28727933/98098204-fce39d80-1ec8-11eb-9c7c-c808f1ff238d.png)
