### ISSUE TITLE
标题块渲染为html后丢失块id信息

### ISSUE THREAD

**Issue by 2234839** [88250/lute#99]
## 描述问题 

 像 h 系列的块会使用文本作为id那么就丢失了块自身的id
我可以定制 块id 该以什么样的属性附加吗？

### 截屏或录像

![图片](https://user-images.githubusercontent.com/28727933/98102461-9c575f00-1ece-11eb-8ea7-002d1531bab9.png)

**Comment by 88250** [comment]
目前 Heading 节点还没有加上 kramdown IAL ID 渲染。Heading 节点的 ID 渲染稍微有点复杂，涉及到目录（ToC）和[自定义 ID](https://ld246.com/article/1583305480675#heading-ids)（`{#custom-id}`）

![image](https://user-images.githubusercontent.com/873584/98126901-0e40a000-1ef1-11eb-82a1-37ac02da27d5.png)

加上 kramdown IAL 的话还没想好覆盖顺序，是 ToC/CustomID 优先呢还是 IAL ID 优先，请问有什么建议吗？

**Comment by 2234839** [comment]
> 
> 
> 目前 Heading 节点还没有加上 kramdown IAL ID 渲染。Heading 节点的 ID 渲染稍微有点复杂，涉及到目录（ToC）和[自定义 ID](https://ld246.com/article/1583305480675#heading-ids)（`{#custom-id}`）
> 
> ![image](https://user-images.githubusercontent.com/873584/98126901-0e40a000-1ef1-11eb-82a1-37ac02da27d5.png)
> 
> 加上 kramdown IAL 的话还没想好覆盖顺序，是 ToC/CustomID 优先呢还是 IAL ID 优先，请问有什么建议吗？

单讲 id 属性的话 优先级应该 CustomID > ToC > IAL ID
另外我希望可以有自定义id为其他属性的方式，例如 data-block-id = *******

**Comment by 88250** [comment]
好主意，统一加个配置项如何：

```golang
// KramdownIALIDName 设置 kramdown 内联属性列表出现 id 属性时的 name(key) 名称，默认为 "id"。
KramdownIALIDName string
```

应该不需要单独为每种节点配置吧？

**Comment by 2234839** [comment]
> 
> 
> 好主意，统一加个配置项如何：
> 
> ```go
> // KramdownIALIDName 设置 kramdown 内联属性列表出现 id 属性时的 name(key) 名称，默认为 "id"。
> KramdownIALIDName string
> ```
> 
> 应该不需要单独为每种节点配置吧？

可以的

**Comment by 88250** [comment]
使用 `lute.SetKramdownIALIDRenderName("data-block-id")` 即可指定，试试看，谢谢。
